### ISSUE TITLE
Cross browser comparison

### ISSUE THREAD

**Issue by Mkhoury** [twg/wikiwash#100]
- In IE v 11.0.17 when writing in the home page text box an 'X' is visible in the text box to allow the user to delete what was written yet this is not visible in Chrome or Firefox.
Same behaviour above is seen for the text box in the wash page

**Comment by tadman** [comment]
This is a [feature of Internet Explorer](https://msdn.microsoft.com/en-us/library/windows/apps/hh465740.aspx) that can be disabled with the `::-ms-clear pseudo-element` selector.

Since it's a default, best left on.
