### ISSUE TITLE
About Modal > 'X': Moves around while user is scrolling

### ISSUE THREAD

**Issue by irfanpirbhai** [twg/wikiwash#111]
On iPhone 6, the `popup-header.close` element lags behind the user's scrolling actions. This is more pronounced on the Chrome browser, but also occurs on Safari. On `iPhone 4 (iOS 7.0) > Safari`, however, the issue is pronounced.

**iPhone 6 > Chrome:**
![ww-x on modal](https://cloud.githubusercontent.com/assets/3782377/6754527/8d6eb0a0-cef3-11e4-9019-17e50dc17e74.gif)

**iPhone 4 > Safari:**
![ww-x on modal-3](https://cloud.githubusercontent.com/assets/3782377/6754486/3ed882e0-cef3-11e4-917b-7b8dc027e981.gif)

---

**Expected Results:**
- The `X` should remain fixed, regardless of a user's scrolling action and speed

**Tested on:**
- iPhone 4S, iOS 7.0.4
- iPhone 6, iOS 8.1
- iPhone 6 Plus, iOS 8.1.3

**Comment by themarkappleby** [comment]
iOS seems to currently have a bug where fixed positioned elements within scrolling (overflow: auto) elements that have the setting `-webkit-overflow-scrolling: touch;` do not work correctly. I have removed the smooth iOS scrolling in the modal to address this issue.

@irfanpirbhai can you please re-test to confirm that the X stays fixed to the top right corner now?

**Comment by irfanpirbhai** [comment]
The `X` is fixed at the top, now, though at the expense of smooth scrolling.

Marking as resolved.

**Tested on:**
- iPhone 6, iOS 8.1, Chrome
