### ISSUE TITLE
Mobile > Landscape > Article View: Header is not fixed

### ISSUE THREAD

**Issue by irfanpirbhai** [twg/wikiwash#114]
On `Landscape` views for mobile devices, the `header` (with search, or without) is not fixed. It is fixed on desktop and `mobile > portrait` orientations.

![ww-landscape articleview headernotfixed](https://cloud.githubusercontent.com/assets/3782377/6755289/57894450-cef8-11e4-87f0-24a3eaeb9416.gif)

---

**Expected Results:**
- The header should remain fixed on landscape orientations

**Tested on:**
- iPhone 4S, iOS 7.0.4
- iPhone 6, iOS 8.1
- Samsung Galaxy Nexus (xhdpi), Android 4.2.1

**Comment by themarkappleby** [comment]
@irfanpirbhai this was intentional. Since the vertical real-estate is so limited in landscape view, I un-fixed the header to allow more room for content to be displayed.

**Comment by irfanpirbhai** [comment]
Makes sense. Thanks for clarifying. Marking as *Invalid*.
