### ISSUE TITLE
Canada map overlaps text making it difficult to read

### ISSUE THREAD

**Issue by larrystaubin** [twg/wikiwash#39]
Enter URL for wikipedia Canada article into Wikiwash page and click Wash
http://en.wikipedia.org/wiki/Canada

After the page fully loads, scroll through the window. Images are separated from text in each of the sections.

In the Economy section, the map overlaps the text (see attached screen shot)

Using Chrome 39 on Windows 8. Screen Resolution is 1366 X 768

The page in Wikipedia renders correctly
![canada image in wikiwash](https://cloud.githubusercontent.com/assets/8523867/5154723/03e80fb4-7239-11e4-9784-7b5257c633dd.png)

**Comment by irfanpirbhai** [comment]
Duplicated by #98. Closing.
