### ISSUE TITLE
Fixed height when started with a small window 

### ISSUE THREAD

**Issue by l4chong** [twg/wikiwash#43]
Steps
1. Adjust browser window to have shortest height
2. Search for anything
3. Adjust browser window to maximum height

![screen shot 2014-12-08 at 12 50 53 am](https://cloud.githubusercontent.com/assets/1330158/5335316/1dd70022-7e75-11e4-9eb7-6b2990945a72.png)

**Comment by irfanpirbhai** [comment]
Appears resolved.

**Tested on:**
- OSX Yosemite, Chrome 40.0, 1366x768 resolution
