### ISSUE TITLE
Deleted wikipedia entry should not be cache

### ISSUE THREAD

**Issue by l4chong** [twg/wikiwash#44]
![screen shot 2014-12-08 at 1 33 57 am](https://cloud.githubusercontent.com/assets/1330158/5335545/61734d86-7e7a-11e4-8f4c-491effa8e051.png)

**Comment by irfanpirbhai** [comment]
Unable to reproduce. Created and deleted an article, and it no longer shows up on WikiWash. Marking as **Resolved**. Feel free to re-open if issue resurfaces.

**Tested on:**
- OSX Yosemite, Chrome 41.0, 1366x768 resolution
