### ISSUE TITLE
Firefox 33.1.1  First two dates are squished 

### ISSUE THREAD

**Issue by l4chong** [twg/wikiwash#46]
Search for 'Consequentialism'

Mac 10.10  Firefox 33.1.1
![screen shot 2014-12-08 at 2 03 57 am](https://cloud.githubusercontent.com/assets/1330158/5335765/d66fbdf0-7e7e-11e4-9de5-050fea605b0c.png)

**Comment by irfanpirbhai** [comment]
Unable to reproduce. Marking as resolved.

**Tested on:**
- OSX Yosemite, Firefox 35.0.1, 1366x768 resolution
