### ISSUE TITLE
Redirected Wiki pages result in errors.

### ISSUE THREAD

**Issue by galaxy1006** [twg/wikiwash#48]
system: MacOS X yosemite 
browser: Chrome 39 and Firefox 34.0.5

(issues found while trying to reproduce the issue with error pages)

By searching keywords that needed to go through a redirect process, page error occurs instead of redirecting to the expected wikipedia page. 

example: if I search “elon musk”, page shows redirecting needed:
![qq20141206-1](https://cloud.githubusercontent.com/assets/9852365/5346122/1ea1ce76-7eeb-11e4-86d3-363525ce93e7.png)

by clicking the redirect, it leads to error page:
![qq20141206-2](https://cloud.githubusercontent.com/assets/9852365/5346163/8ab17cb0-7eeb-11e4-83c5-02be79e704e2.png)
 
then I tried “Elon_Musk” and “https://en.wikipedia.org/wiki/Elon_Musk” with no redirecting needed, both directed to the correct wikipedia page, so the issue is the redirecting process.

For all other phrases that need redirecting, this issue exists as well.

So the search function requires the user to enter the specific url or the correct and accurate phrase without being ambiguous, this potentially affects the usability level of the tool.

**Comment by irfanpirbhai** [comment]
The original issue appears resolved.

Appears resolved.

**Tested on:**
- OSX Yosemite, Chrome 41.0, 1366x768 resolution
