### ISSUE TITLE
Click back button on keyboard the first time could not direct to the origin wikiwash main page

### ISSUE THREAD

**Issue by grandchao** [twg/wikiwash#55]
system: windows 8
browser: google Chrome Version 39.0.2171.65 m

description: Click back keyboard the 1st time produce a non-functional page, like 
![3 1](https://cloud.githubusercontent.com/assets/10171585/5422839/7cdc83da-8267-11e4-8434-d72e4292c278.png)

Click back keyboard the 2nd time will direct to the origin wikiwash main page. 
![3 2](https://cloud.githubusercontent.com/assets/10171585/5422856/a23c6f68-8268-11e4-860e-9bf752132a4a.png)

**Comment by irfanpirbhai** [comment]
Appears resolved.

**Tested on:**
- OSX Yosemite, Chrome 41.0, 1366x768 resolution
