### ISSUE TITLE
Entering # as a search item results in the site constantly loading

### ISSUE THREAD

**Issue by jbs87** [twg/wikiwash#58]
If I enter '#' as a search term, the site constantly loads

![screen shot 2015-01-14 at 10 28 40 am](https://cloud.githubusercontent.com/assets/9323929/5741307/464939f0-9bd8-11e4-96b7-3c3831e82b27.png)

Chrome 39.0.2171.95 (64-bit)
Mac OSX

**Comment by tadman** [comment]
Fixed in release 1.1.

**Comment by irfanpirbhai** [comment]
Appears resolved.

**Tested on:**
- OSX Yosemite, Chrome 41.0, 1366x768 resolution
