### ISSUE TITLE
Redirect not working in cases of ambiguity

### ISSUE THREAD

**Issue by jbs87** [twg/wikiwash#59]
If I enter a search term that has multiple possible results but that Wikipedia does not direct to an article page on searching for that term like 'pg', the redirect that is shown results in an error

![screen shot 2015-01-14 at 10 36 25 am](https://cloud.githubusercontent.com/assets/9323929/5741486/484326e8-9bd9-11e4-951d-8398cf553e81.png)

![screen shot 2015-01-14 at 10 36 08 am](https://cloud.githubusercontent.com/assets/9323929/5741494/51eaa3a6-9bd9-11e4-8c81-ee60f3906336.png)

Chrome 39.0.2171.95 (64-bit)
Mac OSX

**Comment by irfanpirbhai** [comment]
Appears resolved.

**Tested on:**
- OSX Yosemite, Chrome 41.0, 1366x768 resolution
