### ISSUE TITLE
After clicking on an image, clicking back does not work correctly

### ISSUE THREAD

**Issue by jbs87** [twg/wikiwash#61]
After clicking on an image, clicking back does not work correctly.

In the cartoon page
![screen shot 2015-01-14 at 11 04 00 am](https://cloud.githubusercontent.com/assets/9323929/5742036/35502050-9bdd-11e4-9aea-93dc7a08d6b7.png)

Clicking on the picture results in

![screen shot 2015-01-14 at 11 04 10 am](https://cloud.githubusercontent.com/assets/9323929/5742048/46b635dc-9bdd-11e4-877d-7bedacbd9fbb.png)

Trying back once more results in

![screen shot 2015-01-14 at 11 04 20 am](https://cloud.githubusercontent.com/assets/9323929/5742055/515cfe1c-9bdd-11e4-9b05-270f615d350d.png)

Trying back multiple times results in the same result. In the Wikipedia page, clicking on the image and then hitting back works without issue. 

Chrome Version 39.0.2171.95 (64-bit)
Mac OSX

**Comment by tadman** [comment]
Related to Issue #49, Issue #72. Should be fixed as a combination of both of those in release 1.1.

**Comment by irfanpirbhai** [comment]
Appears resolved.

**Tested on:**
- OSX Yosemite, Chrome 41.0, 1366x768 resolution
