### ISSUE TITLE
Mobile site has display issues

### ISSUE THREAD

**Issue by jbs87** [twg/wikiwash#63]
The site on a Galaxy S3 on Chrome has several display issues. In the google search results on the smartphone, the site is indicated to be mobile friendly. Mobile friendly actually appears next to the search result for Wikiwash

![photo on 2015-01-14 at 11 27 am](https://cloud.githubusercontent.com/assets/9323929/5742652/ccc39df0-9be1-11e4-800b-a031380ce70d.jpg)

![photo on 2015-01-14 at 11 26 am](https://cloud.githubusercontent.com/assets/9323929/5742655/d3e2a68a-9be1-11e4-9c2f-3ee0c159e967.jpg)

GalaxyS3

**Comment by irfanpirbhai** [comment]
Also an issue on iOS devices.

**Comment by themarkappleby** [comment]
The mobile formatting has been improved throughout (in release 1.1.0).

**Comment by irfanpirbhai** [comment]
Improved, indeed. :facepunch: Marking as resolved.

**Tested on:**
- iPhone 4S, iOS 7.0.4
- iPhone 6, iOS 8.1
- iPhone 6 Plus, iOS 8.1.3
- Samsung Galaxy Ace (mdpi), Android 2.3.6
- Samsung Galaxy Nexus (xhdpi), Android 4.2.1
- Motorola RAZR VXT885 (hdpi), Android 4.0.4
- LG Nexus 5 (xxhdpi), Android 4.4
