### ISSUE TITLE
Entering an article beginning with & results in an indefinite loading state

### ISSUE THREAD

**Issue by Zajajajaja** [twg/wikiwash#64]
![image](https://cloud.githubusercontent.com/assets/10548253/5759405/b43c89bc-9c9b-11e4-9ee1-429479a1ce9f.png)

**Comment by tadman** [comment]
Fixed in release 1.1.

**Comment by irfanpirbhai** [comment]
Appears resolved.

**Tested on:**
- OSX Yosemite, Chrome 41.0, 1366x768 resolution
