### ISSUE TITLE
After clicking on any link within a page pressing back in Chrome appears to hang the system.

### ISSUE THREAD

**Issue by Zajajajaja** [twg/wikiwash#66]
![image](https://cloud.githubusercontent.com/assets/10548253/5759679/6b64bad2-9c9d-11e4-827d-0d684e2ad2ab.png)
![image](https://cloud.githubusercontent.com/assets/10548253/5759687/78162b30-9c9d-11e4-8b3c-eaf89f3de6ce.png)
![image](https://cloud.githubusercontent.com/assets/10548253/5759707/82361da0-9c9d-11e4-8446-b5922d083c15.png)

**Comment by irfanpirbhai** [comment]
Resolved, and dupe.

**Tested on:**
- OSX Yosemite, Chrome 41.0, 1366x768 resolution
