### ISSUE TITLE
Cross Browsing (CB): The articles are send into continuous loop

### ISSUE THREAD

**Issue by waqasm** [twg/wikiwash#70]
Clicking different links from the searched article result in a continuous loop

Steps to Reproduce:
1. Search for "Canada"
2. Click on "Provinces and Territories of Canada"
3. Click the back button multiple times

Tested on: IE 11, Mozilla Firefox, Google Chrome
![continous loop](https://cloud.githubusercontent.com/assets/10619334/5830785/ca574898-a0f3-11e4-8fe9-bc88a554cf55.PNG)

**Comment by tadman** [comment]
This should be fixed as part of re-working the back-button behaviour, Issue #49.

**Comment by irfanpirbhai** [comment]
Appears resolved.

**Tested on:**
- OSX Yosemite, Chrome 41.0, 1366x768 resolution
