### ISSUE TITLE
Clicking on an image produce an error

### ISSUE THREAD

**Issue by waqasm** [twg/wikiwash#72]
By clicking on a image embedded in an article produce an error

Tested on: IE11, Mozilla Firefox, Google Chrome

Steps to Reproduce:
1. Search "Canada" in the search tab
2. Click on the map image

![map](https://cloud.githubusercontent.com/assets/10619334/5830995/fed56930-a0f6-11e4-849f-26aaf24b32e4.PNG)

**Comment by irfanpirbhai** [comment]
Appears resolved.

**Tested on:**
- OSX Yosemite, Chrome 41.0, 1366x768 resolution
