### ISSUE TITLE
Redirect article are not properly assign to the right article

### ISSUE THREAD

**Issue by waqasm** [twg/wikiwash#73]
The redirect articles after searching produce an error message

Tested on: IE11, Mozilla Firefox, Google Chrome

Steps to Reproduce:
1. Search for "YouTube Channel" in the search area
2. Click on the redirect link to YouTube page

Expected: Produce the actual Wikipedia Page
Actual: Produce an error
![youtube](https://cloud.githubusercontent.com/assets/10619334/5831027/b0fdbdb0-a0f7-11e4-9429-755ebeaaf2b9.PNG)

**Comment by irfanpirbhai** [comment]
Unable to reproduce. Marking as **resolved**.

**Tested on:**
- OSX Yosemite, Chrome 41.0, 1366x768 resolution
