### ISSUE TITLE
Home Screen -> Search bar requires HTML encoded URLs

### ISSUE THREAD

**Issue by Zeao** [twg/wikiwash#75]
Hello,

Tested in Chrome
The serach engine requires HTML encoded URLs.

Reproduction steps:
1) In Wikipedia.org, search for Model-view-controller and you are sent to this URL: http://en.wikipedia.org/wiki/Model-view-controller 
2) Copy this URL and place it into the Search Bar on the home screen and it encodes it to: http://en.wikipedia.org/wiki/ Model%E2%80%93view%E2%80%93controller 

If you search using the encoded URL it works fine and you are directed to the correct page. However, if you search for http://en.wikipedia.org/wiki/Model-view-controller without the encoding you get:
![image](https://cloud.githubusercontent.com/assets/10383734/5895109/342e4c74-a4e3-11e4-8cb8-31ea6c32097a.png)

If my assumption about this is correct, then to resolve this you may need to do the encoding in the controller instead of the view; because if you encode the URL in the view then you'll have to double encode if the user types in the url from memory.

**Comment by irfanpirbhai** [comment]
The wikipedia article referenced above contains em dashes in its title (Model–view–controller). I believe what's occurring here is that URLs containing em dashes are encoded when pasted into the wikiwash searchbar. Currently, when a user attempts to search for an encoded URL (try `http://en.wikipedia.org/wiki/%3F!_(album)`), the associated page is not retrieved, although the article page's search bar correctly decoded the link.

![wikiwash](https://cloud.githubusercontent.com/assets/3782377/6787575/20ecbc28-d16a-11e4-812b-534c6c3149b0.png)

---

**Expected Results:**
- Any valid, encoded URL that is "washed" should successfully retrieve its associated page.

**Tested on:**
- OSX Yosemite, Chrome 41.0, 1366x768 resolution
