### ISSUE TITLE
Result page does not match StyleGuide

### ISSUE THREAD

**Issue by handsomepete** [twg/wikiwash#77]
As per page 1 of the StyleGuide, the Header is incorrect because of the following:

Export Session button should be to the left of the url box. 
There should be previous/next buttons to the right of Removed/Added

**Comment by YangPanQA** [comment]
On top of the issues have been pointed out, the WW logo and text"Show" are missing as per page 1 of the StyleGuide-V03. Please see attached for reference.
![layout issue](https://cloud.githubusercontent.com/assets/10762373/5964655/cde4f222-a7c3-11e4-89f1-84fcac1d9f2a.png)

**Comment by tadman** [comment]
The style guide was largely a suggestion and the implemented site style has diverged from it.
