### ISSUE TITLE
Android Chrome: Layout issues in portrait view mode

### ISSUE THREAD

**Issue by YangPanQA** [twg/wikiwash#80]
Tested browser: Chrome 40.0.2214.89 
Tested device: One Plus One with Android 4.4.4

Several layout issues in portrait view mode:
1. Texts and logo are overlapped
2. "Wash" button is cut off
3. Text format is not in correct

Please see attached screenshot for reference
![chromemobile](https://cloud.githubusercontent.com/assets/10762373/5965422/fadb9c62-a7c9-11e4-861b-33dc0e46cc32.png)

**Comment by themarkappleby** [comment]
The mobile formatting has been improved throughout (in release 1.1.0), including numerous fixes to this page in particular.

**Comment by irfanpirbhai** [comment]
Appears resolved.

*Tested on:*
- Version 1.0.0 (18), 12 Mar 2015, 12:31
- LG Nexus 5 (xxhdpi), Android 4.4
- Samsung Galaxy Nexus (xhdpi), Android 4.2.1
- Motorola RAZR VXT885 (hdpi), Android 4.0.4
- Samsung Galaxy Ace (mdpi), Android 2.3.6
