### ISSUE TITLE
Webpage Enhancement/Concern: All the css and js code are not minified 

### ISSUE THREAD

**Issue by YangPanQA** [twg/wikiwash#82]
Here, minified means all the .js and .css should be in one huge line with minimal space in between. This will help the webpage to meet a higher quality standard.

Ex. go to http://wikiwash.metronews.ca/css/vendor.css, the code is not minified in this case.

Please see attached screenshot for reference.
![vender css](https://cloud.githubusercontent.com/assets/10762373/5965875/85b15522-a7cd-11e4-9f7e-fe24060eb811.png)

**Comment by irfanpirbhai** [comment]
Appears resolved.

**Tested on:**
- OSX Yosemite, Chrome 41.0, 1366x768 resolution
