### ISSUE TITLE
URL Parsing

### ISSUE THREAD

**Issue by PromisedJetpacks** [twg/wikiwash#84]
Description/Reproduction:
Using a full wiki url on WikiWash: "http://en.wikipedia.org/wiki/Ivan_Sirko"  - Returns the proper wiki site.  
Alternatively, using just "Ivan_Sirko" into the WikiWash search bar returns the same proper result.

However, using a string such as "wikipedia.org/wiki/Ivan_Sirko" causes nothing to happen when clicking "WASH".  I believe this is due to how the application is attempting to parse the URL.
Stack Trace:
TypeError: Cannot read property '$route' of undefined
    at vendor.js:25
    at Scope.$get.Scope.$broadcast (vendor.js:10)
    at vendor.js:19
    at processQueue (vendor.js:10)
    at vendor.js:10
    at Scope.$get.Scope.$eval (vendor.js:10)
    at Scope.$get.Scope.$digest (vendor.js:10)
    at Scope.$get.Scope.$apply (vendor.js:10)
    at HTMLInputElement.<anonymous> (vendor.js:13)
    at HTMLInputElement.jQuery.event.dispatch (vendor.js:3)

Additionally, this same sort of URL parsing issue appears to impact the use of foreign language URLs such as https://de.wikipedia.org/wiki/1825

Impact:
It's likely to expect a new user to encounter this issue.  With no error message provided in the UI, the user may be instantly frustrated with a site that appears to broken.

**Comment by tadman** [comment]
Although `en.wikipedia.org` is only supported at this time, the expression to handle this has been relaxed more in the upcoming release 1.1.

**Comment by irfanpirbhai** [comment]
The original issue appears resolved. Breaking out multi-language support into its own issue.
