### ISSUE TITLE
Unescaped characters in request not handled correctly

### ISSUE THREAD

**Issue by tadman** [twg/wikiwash#89]
A mangled URL with unescaped characters causes uncaught errors in the `http` layer.

    TypeError: Request path contains unescaped characters.

**Comment by tadman** [comment]
This is actually via the Socket.io layer. The receiving code needs to be made more robust or malicious requests may crash the server.

**Comment by irfanpirbhai** [comment]
Not sure this is resolved. By typing in "/" in the searchbar, the app crashes.

![wikiwash_ _node_ _50x24_and_developer_tools_-_http___localhost_3000___and_wikiwash](https://cloud.githubusercontent.com/assets/3782377/6789026/b9b31a16-d173-11e4-81bb-40ac0502e40b.png)
