### ISSUE TITLE
Home page Cosmetic/Design Issues

### ISSUE THREAD

**Issue by Mkhoury** [twg/wikiwash#91]
Comparing the website with the style guide V03 (Knowing that the website might have a more suitable design but thought this was worth sharing for a new version of the style guide)
- The wiki wash logo must be centred as shown in the design document
- The sentence (track wikipedia edits in real time...) should be under the logo and both should be centred
- The links How to use wikiwash and what is wikiwash... do not exist in the style guide
- The wash button should be centred and under the text box as shown in the style guide
- The sentence not sure what article to wash, ... does not exist in the style guide
- The about and the copy right are not shown in the home page and the links currently shown don't exist in the document
- Minimizing the browser messes up the page design (this would be fixed when the mobile version is supported but thought it is worth highlighting)

**Comment by tadman** [comment]
The style guide was largely a suggestion and the implemented site style has diverged from it.
