### ISSUE TITLE
Wash page cosmetic/design issues

### ISSUE THREAD

**Issue by Mkhoury** [twg/wikiwash#92]
Comparing the website with the style guide V03:
- WW logo should exist on the top left of the screen next to the wiki wash word
- The 'Show' label should be next to the remove and edit, currently it is before the text box
- The 'export session' button should be before the text box currently it is after the remove and add checkboxes

**Comment by tadman** [comment]
The style guide was largely a suggestion and the implemented site style has diverged from it.
