### ISSUE TITLE
Exported file naming convention and format

### ISSUE THREAD

**Issue by Mkhoury** [twg/wikiwash#96]
- Export session file should have a timestamp along with the file name to better identify the exported file
- I don't think the revision id is significant to the user in the csv file in my opinion it can be removed to simplify the file's content

**Comment by tadman** [comment]
The download filename now shows up as a roughly sanitized version of the page name. This should eliminate the ambiguity here.

**Comment by irfanpirbhai** [comment]
Appears resolved.

**Tested on:**
- OSX Yosemite, Chrome 41.0, 1366x768 resolution
